// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PacketType int32

const (
	PacketType_TYPE_REQUEST  PacketType = 0
	PacketType_TYPE_RESPONSE PacketType = 1
)

var PacketType_name = map[int32]string{
	0: "TYPE_REQUEST",
	1: "TYPE_RESPONSE",
}

var PacketType_value = map[string]int32{
	"TYPE_REQUEST":  0,
	"TYPE_RESPONSE": 1,
}

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}

func (x *PacketType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PacketType_value, data, "PacketType")
	if err != nil {
		return err
	}
	*x = PacketType(value)
	return nil
}

func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

type ResponseType int32

const (
	ResponseType_TYPE_SUCCESS ResponseType = 0
	ResponseType_TYPE_FAIL    ResponseType = 1
)

var ResponseType_name = map[int32]string{
	0: "TYPE_SUCCESS",
	1: "TYPE_FAIL",
}

var ResponseType_value = map[string]int32{
	"TYPE_SUCCESS": 0,
	"TYPE_FAIL":    1,
}

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}

func (x *ResponseType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResponseType_value, data, "ResponseType")
	if err != nil {
		return err
	}
	*x = ResponseType(value)
	return nil
}

func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

type NoReturn struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoReturn) Reset()         { *m = NoReturn{} }
func (m *NoReturn) String() string { return proto.CompactTextString(m) }
func (*NoReturn) ProtoMessage()    {}
func (*NoReturn) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *NoReturn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoReturn.Unmarshal(m, b)
}
func (m *NoReturn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoReturn.Marshal(b, m, deterministic)
}
func (m *NoReturn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoReturn.Merge(m, src)
}
func (m *NoReturn) XXX_Size() int {
	return xxx_messageInfo_NoReturn.Size(m)
}
func (m *NoReturn) XXX_DiscardUnknown() {
	xxx_messageInfo_NoReturn.DiscardUnknown(m)
}

var xxx_messageInfo_NoReturn proto.InternalMessageInfo

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Fail struct {
	Reason               *string  `protobuf:"bytes,1,opt,name=Reason" json:"Reason,omitempty"`
	Code                 *string  `protobuf:"bytes,2,opt,name=Code" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fail) Reset()         { *m = Fail{} }
func (m *Fail) String() string { return proto.CompactTextString(m) }
func (*Fail) ProtoMessage()    {}
func (*Fail) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

func (m *Fail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fail.Unmarshal(m, b)
}
func (m *Fail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fail.Marshal(b, m, deterministic)
}
func (m *Fail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fail.Merge(m, src)
}
func (m *Fail) XXX_Size() int {
	return xxx_messageInfo_Fail.Size(m)
}
func (m *Fail) XXX_DiscardUnknown() {
	xxx_messageInfo_Fail.DiscardUnknown(m)
}

var xxx_messageInfo_Fail proto.InternalMessageInfo

func (m *Fail) GetReason() string {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return ""
}

func (m *Fail) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

//公共参数
type Common struct {
	Version              *string  `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	UserId               *int64   `protobuf:"varint,2,opt,name=UserId" json:"UserId,omitempty"`
	Token                *string  `protobuf:"bytes,3,opt,name=Token" json:"Token,omitempty"`
	Flag                 *int32   `protobuf:"varint,4,opt,name=flag" json:"flag,omitempty"`
	ServerType           *int32   `protobuf:"varint,5,opt,name=ServerType" json:"ServerType,omitempty"`
	Ip                   *string  `protobuf:"bytes,6,opt,name=Ip" json:"Ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Common) Reset()         { *m = Common{} }
func (m *Common) String() string { return proto.CompactTextString(m) }
func (*Common) ProtoMessage()    {}
func (*Common) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{3}
}

func (m *Common) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common.Unmarshal(m, b)
}
func (m *Common) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common.Marshal(b, m, deterministic)
}
func (m *Common) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common.Merge(m, src)
}
func (m *Common) XXX_Size() int {
	return xxx_messageInfo_Common.Size(m)
}
func (m *Common) XXX_DiscardUnknown() {
	xxx_messageInfo_Common.DiscardUnknown(m)
}

var xxx_messageInfo_Common proto.InternalMessageInfo

func (m *Common) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *Common) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Common) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Common) GetFlag() int32 {
	if m != nil && m.Flag != nil {
		return *m.Flag
	}
	return 0
}

func (m *Common) GetServerType() int32 {
	if m != nil && m.ServerType != nil {
		return *m.ServerType
	}
	return 0
}

func (m *Common) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

type Request struct {
	RequestId            *uint64  `protobuf:"varint,1,opt,name=RequestId" json:"RequestId,omitempty"`
	MethodName           *string  `protobuf:"bytes,2,opt,name=MethodName" json:"MethodName,omitempty"`
	Serialized           []byte   `protobuf:"bytes,3,opt,name=Serialized" json:"Serialized,omitempty"`
	Timestamp            *int64   `protobuf:"varint,4,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Timeout              *uint32  `protobuf:"fixed32,5,opt,name=Timeout" json:"Timeout,omitempty"`
	Common               *Common  `protobuf:"bytes,6,opt,name=Common" json:"Common,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *Request) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

func (m *Request) GetSerialized() []byte {
	if m != nil {
		return m.Serialized
	}
	return nil
}

func (m *Request) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Request) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

func (m *Request) GetCommon() *Common {
	if m != nil {
		return m.Common
	}
	return nil
}

type Response struct {
	ResponseId           *uint64       `protobuf:"varint,1,opt,name=ResponseId" json:"ResponseId,omitempty"`
	SubType              *ResponseType `protobuf:"varint,2,opt,name=SubType,enum=base.ResponseType" json:"SubType,omitempty"`
	Serialized           []byte        `protobuf:"bytes,3,opt,name=Serialized" json:"Serialized,omitempty"`
	MsgName              *string       `protobuf:"bytes,4,opt,name=MsgName" json:"MsgName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponseId() uint64 {
	if m != nil && m.ResponseId != nil {
		return *m.ResponseId
	}
	return 0
}

func (m *Response) GetSubType() ResponseType {
	if m != nil && m.SubType != nil {
		return *m.SubType
	}
	return ResponseType_TYPE_SUCCESS
}

func (m *Response) GetSerialized() []byte {
	if m != nil {
		return m.Serialized
	}
	return nil
}

func (m *Response) GetMsgName() string {
	if m != nil && m.MsgName != nil {
		return *m.MsgName
	}
	return ""
}

type Packet struct {
	Type                 *PacketType `protobuf:"varint,1,opt,name=Type,enum=base.PacketType" json:"Type,omitempty"`
	Serialized           []byte      `protobuf:"bytes,2,opt,name=Serialized" json:"Serialized,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{6}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetType() PacketType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PacketType_TYPE_REQUEST
}

func (m *Packet) GetSerialized() []byte {
	if m != nil {
		return m.Serialized
	}
	return nil
}

func init() {
	proto.RegisterEnum("base.PacketType", PacketType_name, PacketType_value)
	proto.RegisterEnum("base.ResponseType", ResponseType_name, ResponseType_value)
	proto.RegisterType((*NoReturn)(nil), "base.NoReturn")
	proto.RegisterType((*Empty)(nil), "base.Empty")
	proto.RegisterType((*Fail)(nil), "base.Fail")
	proto.RegisterType((*Common)(nil), "base.Common")
	proto.RegisterType((*Request)(nil), "base.Request")
	proto.RegisterType((*Response)(nil), "base.Response")
	proto.RegisterType((*Packet)(nil), "base.Packet")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x61, 0x8b, 0xd3, 0x40,
	0x10, 0xbd, 0x6d, 0xb7, 0xcd, 0x75, 0xec, 0x1d, 0x71, 0x11, 0xd9, 0x0f, 0x22, 0x47, 0xf0, 0xc3,
	0x71, 0xc8, 0x89, 0xfd, 0x07, 0x52, 0x72, 0x10, 0xf0, 0x6a, 0xdd, 0x4d, 0x05, 0x3f, 0xc9, 0x9e,
	0x19, 0xcf, 0x70, 0x4d, 0x36, 0x66, 0x53, 0xa1, 0xfe, 0x0c, 0xf1, 0x2f, 0xf9, 0xbf, 0x64, 0x27,
	0x49, 0x1b, 0x44, 0xf0, 0xdb, 0xbc, 0x37, 0x3b, 0xf3, 0xde, 0x9b, 0x05, 0xb8, 0x33, 0x0e, 0xaf,
	0xab, 0xda, 0x36, 0x56, 0x70, 0x5f, 0x47, 0x00, 0xa7, 0x2b, 0xab, 0xb0, 0xd9, 0xd5, 0x65, 0x14,
	0xc0, 0x24, 0x2e, 0xaa, 0x66, 0x1f, 0x2d, 0x80, 0xdf, 0x98, 0x7c, 0x2b, 0x9e, 0xc2, 0x54, 0xa1,
	0x71, 0xb6, 0x94, 0xec, 0x82, 0x5d, 0xce, 0x54, 0x87, 0x84, 0x00, 0xbe, 0xb4, 0x19, 0xca, 0x11,
	0xb1, 0x54, 0x47, 0xbf, 0x18, 0x4c, 0x97, 0xb6, 0x28, 0x6c, 0x29, 0x24, 0x04, 0x1f, 0xb0, 0x76,
	0xf9, 0x61, 0xae, 0x87, 0x7e, 0xe1, 0xc6, 0x61, 0x9d, 0x64, 0x34, 0x3a, 0x56, 0x1d, 0x12, 0x4f,
	0x60, 0x92, 0xda, 0x07, 0x2c, 0xe5, 0x98, 0xde, 0xb7, 0xc0, 0xcb, 0x7c, 0xd9, 0x9a, 0x7b, 0xc9,
	0x2f, 0xd8, 0xe5, 0x44, 0x51, 0x2d, 0x9e, 0x03, 0x68, 0xac, 0xbf, 0x63, 0x9d, 0xee, 0x2b, 0x94,
	0x13, 0xea, 0x0c, 0x18, 0x71, 0x0e, 0xa3, 0xa4, 0x92, 0x53, 0x5a, 0x33, 0x4a, 0xaa, 0xe8, 0x37,
	0x83, 0x40, 0xe1, 0xb7, 0x1d, 0xba, 0x46, 0x3c, 0x83, 0x59, 0x57, 0x26, 0x19, 0x39, 0xe3, 0xea,
	0x48, 0xf8, 0xcd, 0xb7, 0xd8, 0x7c, 0xb5, 0xd9, 0xca, 0x14, 0x7d, 0xb4, 0x01, 0xd3, 0x29, 0xe7,
	0x66, 0x9b, 0xff, 0xc0, 0x8c, 0x8c, 0xce, 0xd5, 0x80, 0xf1, 0xdb, 0xd3, 0xbc, 0x40, 0xd7, 0x98,
	0xa2, 0x22, 0xcb, 0x63, 0x75, 0x24, 0xfc, 0x4d, 0x3c, 0xb0, 0xbb, 0x86, 0x4c, 0x07, 0xaa, 0x87,
	0xe2, 0x45, 0x7f, 0x37, 0x72, 0xfd, 0x68, 0x31, 0xbf, 0xa6, 0x4f, 0x6a, 0x39, 0xd5, 0xf5, 0xa2,
	0x9f, 0x0c, 0x4e, 0x15, 0xba, 0xca, 0x96, 0x8e, 0xac, 0xf4, 0xf5, 0x21, 0xc9, 0x80, 0x11, 0x2f,
	0x21, 0xd0, 0xbb, 0x3b, 0xba, 0x90, 0xcf, 0x71, 0xbe, 0x10, 0xed, 0xce, 0xfe, 0x89, 0xef, 0xa8,
	0xfe, 0xc9, 0x7f, 0x83, 0x49, 0x08, 0x6e, 0xdd, 0x3d, 0x5d, 0x85, 0xb7, 0xdf, 0xd9, 0xc1, 0x68,
	0x05, 0xd3, 0xb5, 0xf9, 0xfc, 0x80, 0x3e, 0x04, 0x27, 0x39, 0x46, 0x72, 0x61, 0x2b, 0xd7, 0xf6,
	0x48, 0x8c, 0xff, 0x43, 0x69, 0xf4, 0xb7, 0xd2, 0xd5, 0x6b, 0x80, 0xe3, 0x8c, 0x08, 0x61, 0x9e,
	0x7e, 0x5c, 0xc7, 0x9f, 0x54, 0xfc, 0x7e, 0x13, 0xeb, 0x34, 0x3c, 0x11, 0x8f, 0xe1, 0xac, 0x63,
	0xf4, 0xfa, 0xdd, 0x4a, 0xc7, 0x21, 0xbb, 0x7a, 0x05, 0xf3, 0x61, 0xaa, 0xc3, 0x90, 0xde, 0x2c,
	0x97, 0xb1, 0xd6, 0xe1, 0x89, 0x38, 0x83, 0x19, 0x31, 0x37, 0x6f, 0x92, 0xb7, 0x21, 0xfb, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x6b, 0x7b, 0xbe, 0xfe, 0x03, 0x03, 0x00, 0x00,
}
