// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package gateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringMessage struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringMessage) Reset()         { *m = StringMessage{} }
func (m *StringMessage) String() string { return proto.CompactTextString(m) }
func (*StringMessage) ProtoMessage()    {}
func (*StringMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *StringMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMessage.Unmarshal(m, b)
}
func (m *StringMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMessage.Marshal(b, m, deterministic)
}
func (m *StringMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMessage.Merge(m, src)
}
func (m *StringMessage) XXX_Size() int {
	return xxx_messageInfo_StringMessage.Size(m)
}
func (m *StringMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StringMessage proto.InternalMessageInfo

func (m *StringMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StringMessage) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type FSReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	File                 string   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FSReq) Reset()         { *m = FSReq{} }
func (m *FSReq) String() string { return proto.CompactTextString(m) }
func (*FSReq) ProtoMessage()    {}
func (*FSReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *FSReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSReq.Unmarshal(m, b)
}
func (m *FSReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSReq.Marshal(b, m, deterministic)
}
func (m *FSReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSReq.Merge(m, src)
}
func (m *FSReq) XXX_Size() int {
	return xxx_messageInfo_FSReq.Size(m)
}
func (m *FSReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FSReq.DiscardUnknown(m)
}

var xxx_messageInfo_FSReq proto.InternalMessageInfo

func (m *FSReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FSReq) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type FSResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FSResp) Reset()         { *m = FSResp{} }
func (m *FSResp) String() string { return proto.CompactTextString(m) }
func (*FSResp) ProtoMessage()    {}
func (*FSResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *FSResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FSResp.Unmarshal(m, b)
}
func (m *FSResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FSResp.Marshal(b, m, deterministic)
}
func (m *FSResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FSResp.Merge(m, src)
}
func (m *FSResp) XXX_Size() int {
	return xxx_messageInfo_FSResp.Size(m)
}
func (m *FSResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FSResp.DiscardUnknown(m)
}

var xxx_messageInfo_FSResp proto.InternalMessageInfo

func (m *FSResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *FSResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{4}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type PingMessage struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingMessage) Reset()         { *m = PingMessage{} }
func (m *PingMessage) String() string { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()    {}
func (*PingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{5}
}

func (m *PingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingMessage.Unmarshal(m, b)
}
func (m *PingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingMessage.Marshal(b, m, deterministic)
}
func (m *PingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingMessage.Merge(m, src)
}
func (m *PingMessage) XXX_Size() int {
	return xxx_messageInfo_PingMessage.Size(m)
}
func (m *PingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_PingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_PingMessage proto.InternalMessageInfo

func (m *PingMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*StringMessage)(nil), "gateway.StringMessage")
	proto.RegisterType((*FSReq)(nil), "gateway.FSReq")
	proto.RegisterType((*FSResp)(nil), "gateway.FSResp")
	proto.RegisterType((*LoginRequest)(nil), "gateway.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "gateway.LoginReply")
	proto.RegisterType((*PingMessage)(nil), "gateway.PingMessage")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x95, 0xd5, 0x26, 0x9b, 0x1d, 0x28, 0x7f, 0x4c, 0xbb, 0xac, 0x42, 0x11, 0xc5, 0x17,
	0x4a, 0x0f, 0xb5, 0x80, 0x13, 0x39, 0x22, 0xd1, 0x72, 0x00, 0x09, 0xb2, 0xe2, 0xc2, 0x05, 0x99,
	0xec, 0xe0, 0x8d, 0xf0, 0xda, 0x6e, 0xec, 0xb4, 0xac, 0xaa, 0x5e, 0x78, 0x05, 0x1e, 0x8d, 0x2b,
	0x47, 0x1e, 0x04, 0xc5, 0xf9, 0xa3, 0x74, 0x25, 0x2e, 0xdc, 0xe6, 0x9b, 0xc9, 0xf7, 0xcb, 0x68,
	0x3e, 0xc3, 0x8e, 0xe0, 0x0e, 0x2f, 0xf8, 0xe6, 0xd8, 0x94, 0xda, 0x69, 0x32, 0x69, 0x65, 0xb2,
	0x2f, 0xb4, 0x16, 0x12, 0x19, 0x37, 0x05, 0xe3, 0x4a, 0x69, 0xc7, 0x5d, 0xa1, 0x95, 0x6d, 0x3e,
	0xa3, 0x2f, 0x61, 0x67, 0xe1, 0xca, 0x42, 0x89, 0x77, 0x68, 0x2d, 0x17, 0x48, 0x76, 0x21, 0x3c,
	0xe7, 0xb2, 0xc2, 0x79, 0x70, 0x10, 0x1c, 0x4e, 0xb3, 0x46, 0x10, 0x02, 0xe3, 0x5c, 0x2f, 0x71,
	0x3e, 0x3a, 0x08, 0x0e, 0xc3, 0xcc, 0xd7, 0x94, 0x41, 0x78, 0xb2, 0xc8, 0xf0, 0xac, 0x1e, 0x2a,
	0xbe, 0xee, 0x1c, 0xbe, 0xae, 0x7b, 0x5f, 0x0b, 0xd9, 0x18, 0xa6, 0x99, 0xaf, 0x69, 0x0a, 0x51,
	0x6d, 0xb0, 0x86, 0xcc, 0x20, 0xb2, 0x8e, 0xbb, 0xca, 0x7a, 0x4f, 0x9c, 0xb5, 0x8a, 0xcc, 0x61,
	0xb2, 0x6e, 0xf6, 0x68, 0x8d, 0x9d, 0xa4, 0x27, 0x70, 0xf3, 0xad, 0x16, 0x85, 0xca, 0xf0, 0xac,
	0x42, 0xeb, 0x48, 0x02, 0x71, 0x65, 0xb1, 0x1c, 0xfc, 0xb7, 0xd7, 0xf5, 0xcc, 0x70, 0x6b, 0x2f,
	0x74, 0xb9, 0x6c, 0x31, 0xbd, 0xa6, 0x29, 0x40, 0xcb, 0x31, 0x72, 0xb3, 0xb5, 0xc7, 0xb4, 0xdf,
	0x63, 0x17, 0x42, 0xa7, 0xbf, 0xa1, 0x6a, 0xed, 0x8d, 0xa0, 0x4f, 0xe1, 0xc6, 0xfb, 0xc1, 0xa5,
	0x12, 0x88, 0x45, 0x89, 0xe8, 0x0a, 0x25, 0xba, 0x15, 0x3a, 0xfd, 0xfc, 0xf7, 0x08, 0x26, 0xa7,
	0x4d, 0x00, 0x64, 0x01, 0xe3, 0xd7, 0xf9, 0x4a, 0x93, 0xd9, 0x71, 0x97, 0xd0, 0xb5, 0x8b, 0x27,
	0xff, 0xe8, 0xd3, 0x07, 0x3f, 0x7e, 0xfd, 0xf9, 0x39, 0xda, 0xa3, 0x77, 0xd8, 0xf9, 0x33, 0x86,
	0xdf, 0xf9, 0xda, 0x48, 0x64, 0x98, 0xaf, 0x74, 0x1a, 0x1c, 0x91, 0xcf, 0x30, 0x3e, 0xfd, 0x1f,
	0xe8, 0x13, 0x0f, 0x7d, 0x4c, 0x1e, 0x0d, 0xa1, 0x22, 0x5f, 0x69, 0x76, 0xe9, 0x93, 0xbe, 0x62,
	0x97, 0x75, 0xb8, 0x57, 0xe4, 0x0d, 0x44, 0x1f, 0x8d, 0xd4, 0x7c, 0x49, 0x6e, 0xf5, 0x28, 0x1f,
	0x77, 0x72, 0xfb, 0x9a, 0xb6, 0x86, 0x3e, 0xf4, 0xcc, 0xfb, 0x94, 0x0c, 0x99, 0x95, 0x37, 0xd7,
	0xab, 0x7e, 0x80, 0xd0, 0x9f, 0x9c, 0xec, 0xf5, 0xc6, 0x61, 0x94, 0xc9, 0xbd, 0xed, 0xb6, 0x91,
	0x1b, 0xba, 0xef, 0x99, 0x33, 0x7a, 0x77, 0xc8, 0x94, 0xf5, 0x3c, 0x0d, 0x8e, 0x5e, 0xc1, 0xa7,
	0x98, 0xb5, 0xa6, 0x2f, 0x91, 0x7f, 0xc8, 0x2f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x54, 0xb2,
	0xc0, 0x97, 0x00, 0x03, 0x00, 0x00,
}
