# 若要加配置、改配置名,请一定在打包脚本 build_linux_yaml_template.py 的模板上也同时加上

INCLUDE: ["config_share.yaml"] # 可以包含多个其他 *.yaml 文件
SERVER_TYPE: 2                     #服务器类型 1-rpc server,2-gateway
SERVER_ID: 2001                    #服务器编号:1000开头
SERVER_NAME: "gateway_server"      #服务器名称
SERVER_ADDR: "127.0.0.1"           #服务器外部地址
SERVER_ADDR_INTERNAL: "127.0.0.1"  #服务器内部地址
LISTEN_PORT_FOR_CLIENT: 9192       #监听连接端口
