// Code generated by entc, DO NOT EDIT.

package ent

import "entgo.io/ent/dialect"

func (c *CarClient) Debug() *CarClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &CarClient{config: cfg}
}

func (c *CardClient) Debug() *CardClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &CardClient{config: cfg}
}

func (c *CityClient) Debug() *CityClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &CityClient{config: cfg}
}

func (c *GroupClient) Debug() *GroupClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &GroupClient{config: cfg}
}

func (c *NodeClient) Debug() *NodeClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &NodeClient{config: cfg}
}

func (c *PostClient) Debug() *PostClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &PostClient{config: cfg}
}

func (c *StreetClient) Debug() *StreetClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &StreetClient{config: cfg}
}

func (c *TenantClient) Debug() *TenantClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &TenantClient{config: cfg}
}

func (c *UserClient) Debug() *UserClient {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	return &UserClient{config: cfg}
}
