// Code generated by entc, DO NOT EDIT.

package ent

import "fmt"

func (c *Car) GoString() string {
	if c == nil {
		return fmt.Sprintf("Car(nil)")
	}
	return c.String()
}

func (c *Card) GoString() string {
	if c == nil {
		return fmt.Sprintf("Card(nil)")
	}
	return c.String()
}

func (c *City) GoString() string {
	if c == nil {
		return fmt.Sprintf("City(nil)")
	}
	return c.String()
}

func (gr *Group) GoString() string {
	if gr == nil {
		return fmt.Sprintf("Group(nil)")
	}
	return gr.String()
}

func (n *Node) GoString() string {
	if n == nil {
		return fmt.Sprintf("Node(nil)")
	}
	return n.String()
}

func (po *Post) GoString() string {
	if po == nil {
		return fmt.Sprintf("Post(nil)")
	}
	return po.String()
}

func (s *Street) GoString() string {
	if s == nil {
		return fmt.Sprintf("Street(nil)")
	}
	return s.String()
}

func (t *Tenant) GoString() string {
	if t == nil {
		return fmt.Sprintf("Tenant(nil)")
	}
	return t.String()
}

func (u *User) GoString() string {
	if u == nil {
		return fmt.Sprintf("User(nil)")
	}
	return u.String()
}
