// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Street is the predicate function for street builders.
type Street func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
